server.port=8099
spring.application.name=oauth2-demo

# Keycloak OAuth2 Client Configuration
spring.security.oauth2.client.registration.keycloak.client-id=demo-app
spring.security.oauth2.client.registration.keycloak.client-secret=cv5WjLrwkYpOkndHsXv57GckXOt02qmfBi5Opk0n6lbVDTcJpZ6wNkzIegHnzFqg8ILtMGh0CwsfYz8vzHHhLw
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8099/login/oauth2/code/keycloak

# Keycloak Provider Configuration
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/demo-keycloak
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

# SpringDoc / Swagger UI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Logging Configuration
logging.level.root=INFO
logging.level.com.keycloak.oauth2_demo=INFO
logging.level.org.springframework.security=WARN

# Tự động xuất log ra file logs/application.log trong project
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

# Pattern log chuẩn trên console và file
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %-40.40logger{39} : %m%n%wEx
