server.port=8099
spring.application.name=oauth2-demo

# Keycloak OAuth2 Client Configuration
spring.security.oauth2.client.registration.keycloak.client-id=demo-app
spring.security.oauth2.client.registration.keycloak.client-secret=cv5WjLrwkYpOkndHsXv57GckXOt02qmfBi5Opk0n6lbVDTcJpZ6wNkzIegHnzFqg8ILtMGh0CwsfYz8vzHHhLw
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8099/login/oauth2/code/keycloak


# Keycloak Provider Configuration (thay my-realm bằng realm của bạn)
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/demo-keycloak
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
